import UserInterface from "../types/user";

export const users: UserInterface[] = [
  { id: 1, name: "tony", topics: ["wild n out", "robert kiyosaki", "star wars", "messi", "uefa champions league"] },
  { id: 2, name: "henry", topics: ["ufc", "star wars", "robert kiyosaki", "messi", "uefa champions league"] },
  { id: 3, name: "blind", topics: ["jon bellion", "wrestling", "cryptocurrency", "messi", "wild n out"] },
  { id: 4, name: "jermaine", topics: ["manchester united", "star wars", "robert kiyosaki", "uefa champions league", "messi"] },
  { id: 5, name: "ossy", topics: ["jon bellion", "formula 1", "wrestling", "uefa champions league", "messi"] },
  { id: 6, name: "jose", topics: ["star wars", "space", "ufc", "uefa champions league", "soccer"] },
  { id: 7, name: "alecia", topics: ["poetry", "star wars", "uefa champions league", "manchester united", "cryptocurrency"] },
  { id: 8, name: "tyler", topics: ["star wars", "ufc", "wrestling", "elon musk", "manchester united"] },
  { id: 9, name: "greg", topics: ["star wars", "jon bellion", "elon musk", "manchester united", "formula 1"] },
  { id: 10, name: "matthew", topics: ["uefa champions league", "ufc", "formula 1", "messi", "manchester united"] },
  { id: 11, name: "david", topics: ["ufc", "messi", "formula 1", "jon bellion", "cryptocurrency"] },
  { id: 12, name: "steverogers", topics: ["cryptocurrency", "wild n out", "uefa champions league", "ufc", "messi"] },
  { id: 13, name: "bryan", topics: ["formula 1", "jon bellion", "ufc", "wrestling", "wild n out"] },
  { id: 14, name: "rex", topics: ["formula 1", "jon bellion", "soccer", "wild n out", "cryptocurrency"] },
  { id: 15, name: "jeff", topics: ["formula 1", "jon bellion", "stock market", "manchester united", "poetry"] },
  { id: 16, name: "ada", topics: ["ufc", "stock market", "cryptocurrency", "poetry", "messi"] },
  { id: 17, name: "grace", topics: ["formula 1", "cryptocurrency", "soccer", "poetry", "messi"] },
  { id: 18, name: "divine", topics: ["space", "ufc", "programming", "poetry", "formula 1"] },
  { id: 19, name: "devaney", topics: ["cryptocurrency", "stock market", "poetry", "uefa champions league", "wild n out"] },
  { id: 20, name: "gray", topics: ["artificial intelligence", "programming", "the voice", "uefa champions league", "poetry"] },
  { id: 21, name: "ashe", topics: ["artificial intelligence", "stock market", "manchester united", "programming", "cryptocurrency"] },
  { id: 22, name: "alexa", topics: ["artificial intelligence", "space", "formula 1", "uefa champions league", "wild n out"] },
  { id: 23, name: "yvonne", topics: ["artificial intelligence", "stock market", "uefa champions league", "cryptocurrency", "manchester united"] },
  { id: 24, name: "bruno", topics: ["artificial intelligence", "formula 1", "the voice", "programming", "elon musk"] },
  { id: 25, name: "esther", topics: ["programming", "soccer", "kim kardashian", "jon bellion", "cryptocurrency"] },
  { id: 26, name: "peace", topics: ["programming", "kim kardashian", "the voice", "soccer", "cryptocurrency"] },
  { id: 27, name: "francisca", topics: ["programming", "ufc", "the voice", "wrestling", "artificial intelligence"] },
  { id: 28, name: "alice", topics: ["programming", "wild n out", "ufc", "the voice", "star wars"] },
  { id: 29, name: "austin", topics: ["programming", "elon musk", "the voice", "wrestling", "jon bellion"] },
  { id: 30, name: "craig", topics: ["space", "poetry", "kim kardashian", "soccer", "robert kiyosaki"] },
  { id: 31, name: "dave", topics: ["programming", "robert kiyosaki", "artificial intelligence", "space", "messi"] },
  { id: 32, name: "mel", topics: ["wrestling", "programming", "the voice", "elon musk", "messi"] },
  { id: 33, name: "john", topics: ["wrestling", "poetry", "stock market", "elon musk", "kim kardashian"] },
  { id: 34, name: "cynthia", topics: ["wrestling", "kim kardashian", "artificial intelligence", "robert kiyosaki", "jon bellion"] },
  { id: 35, name: "daniel", topics: ["space", "elon musk", "star wars", "robert kiyosaki", "manchester united"] },
  { id: 36, name: "ema", topics: ["space", "poetry", "elon musk", "star wars", "robert kiyosaki"] },
  { id: 37, name: "yeshua", topics: ["space", "the voice", "elon musk", "kim kardashian", "soccer"] },
  { id: 38, name: "joy", topics: ["poetry", "the voice", "ufc", "stock market", "soccer"] },
  { id: 39, name: "azeez", topics: ["the voice", "soccer", "stock market", "elon musk", "kim kardashian"] },
  { id: 40, name: "guyy", topics: ["the voice", "elon musk", "robert kiyosaki", "wild n out", "soccer"] },
  { id: 41, name: "martin", topics: ["the voice", "space", "wild n out", "soccer", "stock market"] },
  { id: 42, name: "jameson", topics: ["kim kardashian", "poetry", "wrestling", "manchester united", "formula 1"] },
  { id: 43, name: "ivy", topics: ["artificial intelligence", "programming", "cryptocurrency", "manchester united", "soccer"] },
  { id: 44, name: "claire", topics: ["artificial intelligence", "stock market", "manchester united", "soccer", "wild n out"] },
  { id: 45, name: "uyi", topics: ["poetry", "messi", "space", "jon bellion", "star wars"] },
  { id: 46, name: "mitchell", topics: ["wrestling", "stock market", "uefa champions league", "kim kardashian", "artificial intelligence"] },
  { id: 47, name: "precious", topics: ["wrestling", "stock market", "elon musk", "kim kardashian", "ufc"] },
  { id: 48, name: "ben", topics: ["jon bellion", "space", "kim kardashian", "robert kiyosaki", "ufc"] },
  { id: 49, name: "patrick", topics: ["space", "wild n out", "robert kiyosaki", "uefa champions league", "ufc"] },
  { id: 50, name: "stanley", topics: ["kim kardashian", "artificial intelligence", "star wars", "robert kiyosaki", "space"] }
]